# Setup
name: WWII-player repository
title: WWII player
description: Distribuited World War II a la Wolfenstein on top of Fork-n-Play

# JS and CSS
scripts:
  - octokat
  - esprima
  - js-yaml

styles:
  - style

# Options
excerpt_separator: "\n\n"
exclude: []

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _scss
  style: :compressed

# Syntax highlighting
highlighter: pygments
markdown: kramdown
kramdown:
  auto_ids: true
baseurl: /WWII

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
relative_permalinks: true
